server:
  port: 8091

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/ms
    username: postgres
    password: Ranjeet@123#

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: admin
      password: admin

    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liF5eZz8NnMTZnRc
            client-secret: 668c3ff4acd4c2a2b1794793d3ab3cb2136c39a6
            scope:
              - read:user
              - user:email

product:
  service:
    baseUrl: http://127.0.0.1:8092/

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
