server:
  port: 8091

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/ms
    username: postgres
    password: Ranjeet@123#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

product:
  service:
    baseUrl: http://127.0.0.1:8092/

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
