server:
  port: 8091

spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/ms
    username: postgres
    password: Ranjeet@123#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
