server:
  port: 8092

spring:
  application:
    name: INVENTORY-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/ms_inventory
    username: postgres
    password: Ranjeet@123#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

resilience4j:
  ratelimiter:
    instances:
      myRateLimiter:
        limitForPeriod: 2               # Max 2 calls
        limitRefreshPeriod: 10s        # Every 10 seconds
        timeoutDuration: 0             # Don't wait, fail immediately

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"    # expose all actuator endpoints (e.g., health, metrics, etc.)
#  endpoint:
#    health:
#      show-details: always