server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 🔑 Enable dynamic routing using service names
          lower-case-service-id: true
      routes:
        - id: INVENTORY-SERVICE
          uri: lb://INVENTORY
          predicates:
            - Path=/product/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**